export const endpoints = {
  auth: {
    login: '/api/method/optiflow.api.auth.login',
    verifyOtp: '/api/method/optiflow.api.auth.verify_otp',
    forgotPassword: '/api/method/optiflow.api.auth.forgot_password',
    resetPassword: '/api/method/optiflow.api.auth.reset_password',
    profile: '/api/method/optiflow.api.auth.profile',
  },
  tasks: {
    list: '/api/method/optiflow.api.tasks.list',
    detail: (id: string) => `/api/method/optiflow.api.tasks.detail/${id}`,
    create: '/api/method/optiflow.api.tasks.create',
    update: (id: string) => `/api/method/optiflow.api.tasks.update/${id}`,
  },
  rescue: {
    list: '/api/method/optiflow.api.rescue.list',
    detail: (id: string) => `/api/method/optiflow.api.rescue.detail/${id}`,
    remind: (id: string) => `/api/method/optiflow.api.rescue.remind/${id}`,
    reassign: (id: string) => `/api/method/optiflow.api.rescue.reassign/${id}`,
    escalate: (id: string) => `/api/method/optiflow.api.rescue.escalate/${id}`,
    resolve: (id: string) => `/api/method/optiflow.api.rescue.resolve/${id}`,
  },
  attendance: {
    log: '/api/method/optiflow.api.attendance.log',
    history: '/api/method/optiflow.api.attendance.history',
    correction: '/api/method/optiflow.api.attendance.correction',
    checkIn: '/api/method/optiflow.api.attendance.check_in',
    checkOut: '/api/method/optiflow.api.attendance.check_out',
    submitCorrection: '/api/method/optiflow.api.attendance.submit_correction',
  },
  leave: {
    list: '/api/method/optiflow.api.leave.list',
    apply: '/api/method/optiflow.api.leave.apply',
    approve: (id: string) => `/api/method/optiflow.api.leave.approve/${id}`,
    reject: (id: string) => `/api/method/optiflow.api.leave.reject/${id}`,
    submit: '/api/method/optiflow.api.leave.submit',
    buddyTransfers: '/api/method/optiflow.api.leave.buddy_transfers',
    escalate: (id: string) => `/api/method/optiflow.api.leave.${id}/escalate`,
    archive: (id: string) => `/api/method/optiflow.api.leave.${id}/archive`,
  },
  employees: {
    list: '/api/method/optiflow.api.employees.list',
    detail: (id: string) => `/api/method/optiflow.api.employees.detail/${id}`,
    create: '/api/method/optiflow.api.employees.create',
    update: (id: string) => `/api/method/optiflow.api.employees.update/${id}`,
    delete: (id: string) => `/api/method/optiflow.api.employees.delete/${id}`,
  },
  training: {
    list: '/api/method/optiflow.api.training.list',
    assign: '/api/method/optiflow.api.training.assign',
    progress: (id: string) => `/api/method/optiflow.api.training.progress/${id}`,
    content: (id: string) => `/api/method/optiflow.api.training.content/${id}`,
    markComplete: (id: string) => `/api/method/optiflow.api.training.complete/${id}`,
  },
  tickets: {
    list: '/api/method/optiflow.api.tickets.list',
    detail: (id: string) => `/api/method/optiflow.api.tickets.detail/${id}`,
    create: '/api/method/optiflow.api.tickets.create',
    update: (id: string) => `/api/method/optiflow.api.tickets.update/${id}`,
    addComment: (id: string) => `/api/method/optiflow.api.tickets.comment/${id}`,
    close: (id: string) => `/api/method/optiflow.api.tickets.${id}/close`,
    reopen: (id: string) => `/api/method/optiflow.api.tickets.${id}/reopen`,
    assign: (id: string) => `/api/method/optiflow.api.tickets.${id}/assign`,
    escalate: (id: string) => `/api/method/optiflow.api.tickets.${id}/escalate`,
  },
  worklists: {
    list: '/api/method/optiflow.api.worklists.list',
    create: '/api/method/optiflow.api.worklists.create',
    update: (id: string) => `/api/method/optiflow.api.worklists.update/${id}`,
  },
  departments: {
    list: '/api/method/optiflow.api.departments.list',
    create: '/api/method/optiflow.api.departments.create',
    update: (id: string) => `/api/method/optiflow.api.departments.update/${id}`,
  },
  notifications: {
    list: '/api/method/optiflow.api.notifications.list',
    markRead: (id: string) => `/api/method/optiflow.api.notifications.read/${id}`,
    markAllRead: '/api/method/optiflow.api.notifications.read_all',
  },
} as const
